package:
    name: corenlp
    version: "0.5"

source:
    git_url: https://github.com/EducationalTestingService/stanford-thrift.git
    git_tag: stanford-thrift-operational-0.5

build:
    script: python setup.py install

requirements:
    build:
        - python
        - thrift
        - setuptools
    run:
        - python
        - thrift
        - setuptools

test:
    imports:
        - corenlp